### ISSUE TITLE
Is it possible to add dual Y?

### ISSUE THREAD

**Issue by JohnFajardo** [narasak/parrot_3d#1]
I'm anayzing the desing of this printer and I like it so far. However, I've never been a big fan of a single Y axis rail. Can I add two of them?

**Comment by narasak** [comment]
For the Parrot 3D single linear rail for Y-Axis is better.
 But you can use another design of dual linear rail for Y-Axis wit no problem.

**Comment by SimonTil** [comment]
Dual Y is possible, just like Dual Z, Dual E, etc. You need a couple of modifications in the Marlin firmware:
1) in case you want to run **both stepper motors on a single stepper driver** (because of not enough stepper driver ports), you have to
a) Increase the current `#define Y_CURRENT`. This can be found in the file `Configuration_adv.h`.
b) Manufacturers like BigTreeTech sell stepper parallel dividers. You need this module to run 2 steppers on 1 stepper driver.
c) In case one of the steppers run in the wrong direction, you have to use a multi-meter to find out the coils of the stepper motor so you can switch the `+` and `-` side to invert the steppers' direction.
d) Cool down the stepper drivers even harder, since high currents cause more heat.
2) In case you want to run **both stepper drivers through separate stepper drivers**, you have to enable `#define Y2_DRIVER_TYPE` and set the correct driver. It should be connected on the next port after the last extruder (the following order is used: X, Y, Z, E0, E1, E2, E3, E4, ..., X2, X3, ..., Y2, Y3, ..., Z2, Z3, ...). If that sucks up, you have to do some pin modifications. Don't worry, it's not too hard and we are here to help you in case that blows up the firmware.
Make sure to set the STEP, DIR, EN, and CS pin correctly. You can find it in `Marlin/src/pins/<name_of_chip>/<name_of_board>/pins_....h`. You can find pinout schemes everywhere on the interwebz.

I'm working on a derivative of this amazing design that has two smaller Y motors and a single rail. I'm doing this, so I can use more power to move the bed (simply since I can run the motors a bit hotter without requiring extra cooling for the stepper drivers).
Hope this was helpful. Have a nice day!
